SELECT 
    u.NOMBRE || ' ' || u.APELLIDO AS nombre_completo,
    c.NOMBRE AS nombre_curso
FROM 
    CURSOS_ESTUDIANTES ce
    JOIN CALENDARIO_CURSOS cal ON ce.ID_CALENDARIO = cal.ID_CALENDARIO
    JOIN USUARIOS u ON ce.ID_USUARIO = u.ID_USUARIO
    JOIN CURSOS c ON cal.ID_CURSO = c.ID_CURSO

ORDER BY 
    u.NOMBRE, u.APELLIDO;